### ISSUE TITLE
Question: There is any way of getting a already initializes store by  string path?

### ISSUE THREAD

**Issue by rodzappa** [state-adapt/state-adapt#18]
Hi @mfp22,

I've tried this:
    
```
this.store = this.adapt.select(this.featureName, this.createStateAdapter());

if (!this.store) {
  this.store = this.adapt.init(
    [this.featureName, this.createStateAdapter(), initialState],
    {
      sendCommand: this.commandSentSourceList,
      acceptCommand: this.commandAcceptedSourceList,
      throwError: this.errorThrown$,
    }
  );
}

...

private createStateAdapter() {
  return createAdapter<CommandState<T>>()({
    sendCommand: (state, payload: any) => ({
      ...state,
      waiting: true,
      error: null,
    }),
    acceptCommand: (state, cmdStr: string) => ({
      ...state,
      waiting: false,
      error: null,
    }),
    throwError: (state, error: Error) => ({
      ...state,
      error,
      waiting: false,
      entity: null,
      list: [],
    }),
    selectors: {
      getWaiting: (state) => state.waiting,
      getError: (state) => state.error,
    },
  });
}

```
This is avoiding colision path error been throing, if the store is already initilized.
The selectors are working too, though the redux tool stopped showing state changes.
It's appears never enter on adapt.init flow, due to adapt.select always return a store.

Could you help me?

**Comment by mfp22** [comment]
`select` doesn't create a store. It just gives access to state selectors. I renamed it to `spy` and will be releasing that update in some version before the 1.0 release. I thought `spy` was better at communicating the purpose of it. You're just accessing state, not triggering anything to happen. 

`this.store` is getting created every time, so `if (!this.store)` will always be false and the real store won't get created. 

Where is that state path being used already? If it's already being initialized somewhere else, you should probably reference that already-created store.

**Comment by rodzappa** [comment]
I initialized the store throught a factory on component class attributes.
I'm reusing same component to include and to edit entities.
When I include a entity, I check the source action from command accepted to re-route the component in edit way.

On cmdIncluirAccepted$ I get the generated entity ID from backend, to get it from reactive query by startObserver method (this encapsulates FireStore connection).

Checking redux tools, my store is been correctly destroyed before been initialized again on component reload, but state adapter is throwing colision path error on console.

Aside the error throwing, the store continues working without any issues, so I think the bug is on checking step of path colision on state-adapter.

Follow relevant component code:

```
export class FabricanteEditComponent implements OnInit, OnDestroy {
  constructor(
    private router: Router,
    private activatedRoute: ActivatedRoute,
    private uiStateService: UiStateService,
    private dialog: MatDialog,
    private snackBar: MatSnackBar,
    private stateServiceFactory: FabricanteStateServiceFactory
  ) {}

  private queryReactiveService =
    this.stateServiceFactory.createQueryReactiveEntityStateService(
      'FabricanteEditReactiveQRY'
    );

  private commandService =
    this.stateServiceFactory.createCommandStateService('FabricanteEditCMD');

  uid?: string;

  fabricante$ = this.queryReactiveService.adapter.store.getEntity();
  fabricanteError$ = this.queryReactiveService.adapter.store.getError();

  cmdWaiting$ = this.commandService.adapter.store.getWaiting();
  cmdError$ = this.commandService.adapter.store.getError();
  cmdAlterarAccepted$ = this.commandService.fabricanteAlterarCommandAccepted$;
  cmdIncluirAccepted$ = this.commandService.fabricanteIncluirCommandAccepted$;
  cmdExcluirAccepted$ = this.commandService.fabricanteExcluirCommandAccepted$;

  private componentDestroyed = new Subject<void>();
  private formStatus: FormControlStatus = 'PENDING';

  ngOnInit(): void {
    // obter parâmetro de rota e decidir se busca entidade
    this.uid = this.activatedRoute.snapshot.params.uid;
    if (this.uid) {
      this.queryReactiveService.startObserver(this.uid);
    }

    // observer de erro de obtenção da entidade
    this.fabricanteError$
      .pipe(takeUntil(this.componentDestroyed))
      .subscribe((error: Error | null) => {
        if (!!error) {
          DialogNotifyComponent.openDialog(
            this.dialog,
            error.message,
            'error'
          ).subscribe(() => {});
        }
      });

    // observer de espera de comando
    this.cmdWaiting$
      .pipe(takeUntil(this.componentDestroyed))
      .subscribe((waiting) => {
        if (waiting) {
          DialogLoadingComponent.openDialog(this.dialog, this.cmdWaiting$);
        }
      });

    // observer de erro de execução de comando
    this.cmdError$
      .pipe(takeUntil(this.componentDestroyed))
      .subscribe((error: Error | null) => {
        if (!!error) {
          DialogNotifyComponent.openDialog(
            this.dialog,
            error.message,
            'error'
          ).subscribe(() => {});
        }
      });

    // observer de comando de alteração aceito
    this.cmdAlterarAccepted$
      .pipe(takeUntil(this.componentDestroyed))
      .subscribe(() => {
        this.snackBar.open('Fabricante alterado com sucesso', 'Fechar', {
          duration: 5000,
        });
      });

    // observer de comando de inclusão aceito
    this.cmdIncluirAccepted$
      .pipe(takeUntil(this.componentDestroyed))
      .subscribe((action: Action<string>) => {
        this.snackBar.open('Fabricante incluído com sucesso', 'Fechar', {
          duration: 5000,
        });
        void this.router.navigate(['../' + action.payload], {
          relativeTo: this.activatedRoute,
        });
      });

    // observer de comando de exclusão aceito
    this.cmdExcluirAccepted$
      .pipe(takeUntil(this.componentDestroyed))
      .subscribe(() => {
        this.snackBar.open('Fabricante excluído com sucesso', 'Fechar', {
          duration: 5000,
        });
        this.goUp();
      });
  }

  ngOnDestroy(): void {
    this.queryReactiveService.destroy();
    this.componentDestroyed.next();
    this.componentDestroyed.complete();
  }

  goUp(): void {
    void this.router.navigate(['..'], {
      relativeTo: this.activatedRoute,
    });
  }

  new(): void {
    void this.router.navigate(['../new'], {
      relativeTo: this.activatedRoute,
    });
  }

  toggleMenu(): void {
    this.uiStateService.toggleMenu();
  }

  submit(fabricante: FabricanteDto): void {
    if (fabricante.fabricanteId) {
      this.commandService.fabricanteAlterar(fabricante);
    } else {
      this.commandService.fabricanteIncluir(fabricante);
    }
  }

  delete(): void {
    if (this.uid) {
      DialogConfirmComponent.openDialog(
        this.dialog,
        'Deseja excluir esse fabricante?',
        'warning'
      ).subscribe((result: boolean) => {
        if (result && this.uid) {
          this.commandService.fabricanteExcluir(this.uid);
        }
      });
    }
  }

  setFormStatus(status: FormControlStatus) {
    this.formStatus = status;
  }

  canExclude(): boolean {
    return !!this.uid && this.formStatus === 'VALID';
  }

  canNew(): boolean {
    return !!this.uid && this.formStatus === 'VALID';
  }
}

```

**Comment by rodzappa** [comment]
To my mind, could there be a optional parameter on sore init method to return the previous same path store, instead of throwing colision path error.

**Comment by mfp22** [comment]
It's really a shame Angular Material doesn't have declarative APIs for global components like dialogs, toasts, etc. In fact most Angular component libraries don't. Most React, Vue and Svelte component libraries do. If you're interested I'll share a wrapper component I wrote for Angular Material that makes those dialogs declarative. I don't have one for the other imperative APIs, unfortunately. The incredible thing to me is it seems like Angular devs are okay with the imperative APIs. 

Anyway, are both component instances on the same page at the same time? If so, then you want two stores because you are managing 2 separate states. You can still define it in the component and set the path string dynamically so it points to 2 separate states in the global store. 

If you only show 1 component at a time, the store will be removed when everything in the component unsubscribes, so there shouldn't be a path collision issue. This assumes the unsubscribe runs before the new subscriptions run. 

If I were to consider theoretically returning existing stores when developers try to create a store that already exists, it would create an implicit dependency. The path would become the reference to the other store, and TypeScript can't help with that. So you could delete the other instance of the store and break the 2nd user of the store. It would create the store, but it's unknown if it depended on the original state being updating by the original sources. It's a weird scenario. It's better to just put one store in a service and inject it into multiple components. Except here, you are using 2 instances of the same component, so you could either use 1 store only or use component inputs to differentiate the path. 

If you still think there's a problem with StateAdapt, can you please reproduce the issue in a very simple example on StackBlitz?
