### ISSUE TITLE
Docs: improve imports/exports

### ISSUE THREAD

**Issue by sysmat** [state-adapt/state-adapt#26]
1. https://www.npmjs.com/package/@state-adapt/core has version 0.57.0, but stack blitz use 0.48.0
2. error TS2305: Module '"@state-adapt/core"' has no exported member 'defaultStoreProvider'.
3. error TS2305: Module '"@state-adapt/core"' has no exported member 'toSource'.

**Comment by sysmat** [comment]
#  0.57.0
-  import { defaultStoreProvider } from '@state-adapt/angular';
- import { toSource } from '@state-adapt/rxjs';

- but I get ng error: 

```
instrument.js:108 Error: NG0203: inject() must be called from an injection context such as a constructor, a factory function, a field initializer, or a function used with `EnvironmentInjector#runInContext`. Find more at https://angular.io/errors/NG0203
    at injectInjectorOnly (core.mjs:4775:15)
    at ɵɵinject (core.mjs:4786:12)
    at inject (core.mjs:4879:12)
    at adapt (state-adapt-angular.mjs:17:28)
    at SetDeleteUserComponent.ngOnInit (set-delete-user.component.ts:57:28)
```

**Comment by mfp22** [comment]
Not sure which StackBlitz demo you're talking about, but I should just check all them for updates.

`adapt` has to be called inside a component or service because it uses the `inject` function. Here's an article I found explaining it https://netbasal.com/unleash-the-power-of-di-functions-in-angular-2eb9f2697d66

**Comment by sysmat** [comment]
- this example: https://stackblitz.com/edit/angular-ivy-jwt8jh?file=src%2Fapp%2F1-simple-state.component.ts
- I use it in component, which is part of one module, which is lazy loded
- Component is as ng-boostrap modal, which is instance:

```typescript
...
private modalService: NgbModal,
...
this.modalService.open(SetDeleteUserComponent);
```
- and component:

```typescript
import { Component, OnInit } from '@angular/core';
import { FormBuilder, FormControl, FormGroup } from '@angular/forms';
import { NgbActiveModal } from '@ng-bootstrap/ng-bootstrap';
import { adapt } from '@state-adapt/angular';
import { createAdapter } from '@state-adapt/core';
import { toSource } from '@state-adapt/rxjs';

@Component({
  selector: 'app-set-delete-user',
  templateUrl: './set-delete-user.component.html',
  styleUrls: ['./set-delete-user.component.css']
})
export class SetDeleteUserComponent implements OnInit {

  username: string;
  days = 7;
  form!: FormGroup<{ days: FormControl<number> }>;
  when: number;

  name1Store;

  constructor(
    public readonly activeModal: NgbActiveModal,
    private readonly fb: FormBuilder
  ) {
  }

  ngOnInit(): void {

    let today = new Date();
    this.when = today.setDate(today.getDate() + this.days);

    this.form = this.fb.group({
      days: new FormControl(7, { nonNullable: true })
    });

    this.daysCtrl
      .valueChanges
      .subscribe(days => {
        today = new Date();
        this.when = today.setDate(today.getDate() + days);
      });

    const daysFromCtrl$ = this.daysCtrl
      .valueChanges.pipe(
        toSource('[name] nameFromServer$') // Annotate for Redux Devtools
      );

    const whenAdapter = createAdapter<number>()({
      selectors: {
        when: (days) => {
          const t = new Date();
          return this.when = t.setDate(t.getDate() + days);
        }
      },
    });

    this.name1Store = adapt(['when', 7, whenAdapter], daysFromCtrl$);
  }

  get daysCtrl() { return this.form.controls.days; }

  setUserToBeDeleted(): void {
    this.activeModal.close(this.daysCtrl.value);
  }

}
```

**Comment by sysmat** [comment]
- even when using injcet, I get error

 ```typescript
...
  name1Store;
  adapt;

  constructor(
    public readonly activeModal: NgbActiveModal,
    private readonly fb: FormBuilder
  ) {

    this.adapt = inject(adapt);
  }

 ngOnInit(): void {
  ...
  this.name1Store = this.adapt(['when', 7, whenAdapter], daysFromCtrl$);
 }
```
- error:
```
NullInjectorError: R3InjectorError(AppModule)[adapt -> adapt -> adapt]: 
  NullInjectorError: No provider for adapt!
    at NullInjector.get (core.mjs:6359:27)
    at R3Injector.get (core.mjs:6786:33)
    at R3Injector.get (core.mjs:6786:33)
    at R3Injector.get (core.mjs:6786:33)
    at ChainedInjector.get (core.mjs:13769:36)
    at lookupTokenUsingModuleInjector (core.mjs:3293:39)
    at getOrCreateInjectable (core.mjs:3338:12)
    at ɵɵdirectiveInject (core.mjs:10871:12)
    at ɵɵinject (core.mjs:4786:12)
    at inject (core.mjs:4879:12)
    at new SetDeleteUserComponent (set-delete-user.component.ts:28:22)

```

**Comment by mfp22** [comment]
This isn't specific to StateAdapt. If you tried to inject any provider, you'd get this problem. Whether you used `inject` or `constructor(private whateverService: WhateverService) {}`. At least I believe so. `adapt` uses `inject` internally; you don't inject it like that. You just use it, and it uses `inject` inside. Internally it's injecting `AdaptCommon`. So if you wanted to you could try injecting it like `constructor(private adapt: AdaptCommon) {}`. And you can import `AdaptCommon` from `@state-adapt/rxjs` I think. But you'll probably get the same problem. 

Is the modal component imported in a module? 

Angular should know to provide `AdaptCommon`... maybe the way it's instantiated with the modal service, `inject` doesn't work. I guess try `constructor(private whateverService: WhateverService) {}` and see what happens?

**Comment by sysmat** [comment]
- SetDeleteUserComponent is in a declarations of that module
- when using `private adapt: AdaptCommon` in constructor then it works with `this.adapt.init`

@mfp22 thx

**Comment by mfp22** [comment]
Interesting. Well I'll update the docs then...

**Comment by sysmat** [comment]
- docs are better
- but stack blitz dosen't use latest versions, is there a reason?
- https://stackblitz.com/edit/state-adapt-angular?file=src%2Fapp%2Fapp.module.ts
- https://stackblitz.com/edit/state-adapt-angular-with-ngxs?file=src%2Fapp%2Fapp.module.ts
- ...

**Comment by mfp22** [comment]
I'm sweeping through all the docs right now because I have a lot of updates. I'll check the StackBlitz links too. I just barely updated the StackBlitz demo from the home page. I'll have this done within 2 days.
