### ISSUE TITLE
typescript 4.8.4 can't infer type for `adapt.init`

### ISSUE THREAD

**Issue by sysmat** [state-adapt/state-adapt#27]
- in adatp.d.ts are a lot of intersections and unions maybe defined as type alias
- typescript 4.8.4 can't infer type for `adapt.init`
- https://state-adapt.github.io/concepts/stores I can't see any declaration of store type
- is there any better way to declare type of store?

**Comment by mfp22** [comment]
Is it unable to find detect which overload you're trying to use? `init`  has like 7 overloads until the version I'm about to release. I deprecated 3 of them before this version, and I deleted them in this next version, 0.58.0. It makes TypeScript have an easier time seeing exactly what's wrong. I'll have the release out this weekend.

Another thing to check is that your import is correct 

If you're sure everything is set up correctly, I'd like to know everything about the environment you're in. Like, StackBlitz, node version, etc. If possible a reproduction would help.

**Comment by mfp22** [comment]
Oh, I see.

I never declare the store and assign it later. It's not really "declarative", meaning single source of truth. I like to have one place for it to be defined. I also try to avoid lifecycle hooks as much as possible. These are common patterns in Angular, but it isn't the highest quality of code.

I looked at your code again and it doesn't look like there's a need for any of it to be inside an `ngOnInit`. I would move it outside and define everything where it's declared.

However, an alternative would also be to keep the store inside ngOnInit and only assign an observable from it to the class. So like
```
when$: Observable<number>;
//... 
  this.when$ = store.when$;
```

Other good tips for reactivity would be
- Don't declare variables with `let`; don't reassign variables. To know what a variable is, you only need to look at its declaration
- Don't manually `subscribe` to observables

If you're interested I could share how I'd write the code from the other issue you opened.

Anyway, I'm going to officially close this issue with this answer: Don't declare store types. Just define them where you declare them, and rely on type inference. If you need anything Angular doesn't give you until later, make it into a source, and have the store react to it asynchronously.

**Comment by sysmat** [comment]
- I refactor it like that:

```typescript
export class SetDeleteUserComponent {

  username: string;
  days = 7;
  form: FormGroup<{ days: FormControl<number> }> = this.fb.group({
    days: new FormControl(7, { nonNullable: true })
  });

  daysFromCtrl$ = this.daysCtrl
    .valueChanges.pipe(
      toSource('[days] daysFromForm$') // Annotate for Redux Devtools
    );

  whenAdapter = createAdapter<number>()({
    selectors: {
      when: (days) => {
        const t = new Date();
        return t.setDate(t.getDate() + days);
      }
    },
  });

  whenStore = this.adapt.init(['when', this.days, this.whenAdapter], this.daysFromCtrl$);

  constructor(
    public readonly activeModal: NgbActiveModal,
    private readonly fb: FormBuilder,
    private readonly adapt: AdaptCommon
  ) {
  }

  get daysCtrl() { return this.form.controls.days; }

  setUserToBeDeleted(): void {
    this.activeModal.close(this.daysCtrl.value);
  }

}

```

**Comment by mfp22** [comment]
Looks good. That's pretty much how I'd do it.

I wish modals could be in HTML instead of methods though. Angular is the only framework that does it this way.
