### ISSUE TITLE
Little mistake in product.service.ts

### ISSUE THREAD

**Issue by RYAZHAPOVILNUR** [state-adapt/state-adapt#28]
<img width="1303" alt="image" src="https://user-images.githubusercontent.com/42508500/218951326-e143cf28-7d35-4f44-9fe9-ea6d3718df06.png">

**Comment by mfp22** [comment]
Nope, this is actually on purpose :)

When you add a product, it gets removed from 'products' and added to 'cart'. You can see the other half of this below in the cart store.

Thanks for trying to be helpful though! Let me know if you have any questions.
