### ISSUE TITLE
Explore removing overloads for StateAdapt.adapt

### ISSUE THREAD

**Issue by mfp22** [state-adapt/state-adapt#45]
The API for `StateAdapt.adapt` has been mostly the same for 2 years. But I've received feedback from a few people that the overloads are confusing. I've seen that the TypeScript errors can be very confusing as well. A couple of people have also said they want `path` to be optional, and the current syntax would make that very difficult. 

So, I believe StateAdapt.adapt should move to only 1 overload, with 3 possibilities for 2nd argument: undefined, adapter or options. Here is each existing overload and the new syntax:

## `1. adapt(path, initialState)`

```typescript
// old
const count1 = adapt('count1', 4);

// new
const count1 = adapt(4);
```

## `2. adapt([path, initialState], adapter)`
```typescript
// old
const count2_2 = adapt(['count2_2', 4], {
  increment: count => count + 1,
  selectors: {
    isEven: count => count % 2 === 0,
  },
});

// new
const count2_2 = adapt(4, {
  increment: count => count + 1,
  selectors: {
    isEven: count => count % 2 === 0,
  },
});
```

## `3. adapt([path, initialState], sources)`

```typescript
// old
const count3 = adapt(
  ['count3', 4],
  http.get('/count/').pipe(toSource('http data')),
);

// new
const count3 = adapt(4, {
  sources: http.get('/count/').pipe(toSource('http data')),
});
```

## `4. adapt([path, initialState, adapter], sources)`

```typescript
// old
const adapter4 = createAdapter<number>()({
  increment: count => count + 1,
  selectors: {
    isEven: count => count % 2 === 0,
  },
});
const count4 = adapt(['count4', 4, adapter4], watched => {
  return {
    set: watched.state$.pipe(delay(1000), toSource('tick$')),
  };
});

// new
const count4 = adapt(4, {
  path: 'count4',
  adapter: {
    increment: count => count + 1,
    selectors: {
      isEven: count => count % 2 === 0,
    },
  },
  sources: watched => {
    return {
      set: watched.state$.pipe(delay(1000), toSource('tick$')),
    };
  },
});
```

## Implementation

I had to use a trick to get inference to work. Here's the type implementation:

```typescript
  adapt<State, S extends Selectors<State>, R extends ReactionsWithSelectors<State, S>>(
    initialState: State,
    second?: (R & { selectors?: S, adapter?: never, sources?: never, path?: never }) | {
      path?: string;
      adapter?: R & { selectors?: S };
      sources?: SourceArg<State, S, R>;
    }
  ): SmartStore<State, S & WithGetState<State>> & SyntheticSources<R> {
```

## Discussion

What I like about this change:
1. The new `sources` syntax taking a function for recursive sources. See #44 
2. The optional `path`, enabled by 1. For now it will show up in DevTools as `0`, `1`, etc. Automatically chosen path. And maybe it can get smarter over time. But if necessary, can specify path. 
3. Only 1 overload creates much better TS warnings.
4. Simpler for newcomers.
5. Leaves room for more options. 2 come to mind already: `sinks` and `resetOnRefCount0` with the option to keep state in cache for a certain time after all unsubscribes, similar to the same option in `share()`
6. It enables even more incremental syntax than before. It's a smaller gap from `useState(0)` or `signal(0)` to `adapt(0, { increment: n => n + 1 })`. 

What I hate about it:
It's a breaking change. I will try to find a way to make migrating easier. I myself would benefit from migration tools because I have so many projects I will want to update. 

## Plans

Before this, I will add the new source function syntax inspired by #44, add the new injectable function from that discussion, and release that as 1.2.0. Then I'll fix #38 and release that in 1.2.1. 

Since this issue is a breaking change in a main feature, I will make this a major version bump to StateAdapt 2.0. 

All of this can be done before adding signal features for Angular, which will require Angular 16+, so I will release that in version 2.1.

**Comment by mfp22** [comment]
I'll look into this. I'll experiment with it and see if type inference still works as well with it.

Btw, I really recommend using Redux devtools. It provides I think 40% of the value of StateAdapt. But it would be almost useless without annotated sources.

I can make a guess and provide it a pretty useful default path for stores, but I can't do that with sources.

**Comment by DmitryEfimenko** [comment]
I'll give Redux devtools another try!

**Comment by pBouillon** [comment]
Speaking about Redux Devtools, I wonder: one of the main success of NgRx has been [Component Stores](https://ngrx.io/guide/component-store) because it is easy to just drop along an existing component, without tying this up to devtools (which might be a good thing or not) , global state, or else.

I wonder: could `adapt` provide an (overload | parameter | other) to achieve the same behaviour?

Just an idea but it could be great for StateAdapt to also offer the possiblity of a component-scoped state management system and this (potentially) breaking change might be an opportunity to introduce it.

**Comment by mfp22** [comment]
> Speaking about Redux Devtools, one of the main success of NgRx has been [Component Stores](https://ngrx.io/guide/component-store) because it is easy to just drop along an existing component, without tying this up to devtools (which might be a good thing or not) , global state, or else.
> 
> I wonder: could `adapt` provide an (overload | parameter | other) to achieve the same behaviour?
> 
> Just an idea but it could be great for StateAdapt to also offer the possiblity of a component-scoped state management system and this (potentially) breaking change might be an opportunity to introduce it.

I don't see a point. Initial setup is not very hard and there are no benefits beyond that. Actually there are other problems CS has always had that I specifically engineered StateAdapt to avoid, with help of a global store underneath. Now with this new syntax, the fact that there is a global store at all is completely hidden after setup and until you choose a global `path`.

**Comment by jits** [comment]
@mfp22 —

> […] Actually there are other problems CS has always had that I specifically engineered StateAdapt to avoid, with help of a global store underneath. […]

Do you have a blog post / video / etc. with more details? I'm curious to hear more.

**Comment by mfp22** [comment]
Most of them use RxJS for derived state, which has this problem https://dev.to/this-is-angular/i-changed-my-mind-angular-needs-a-reactive-primitive-n2g#oh-yeah-rxjs-actually-sucks-at-that

**Comment by mfp22** [comment]
https://github.com/state-adapt/state-adapt/commit/18ee5ffc958930eb8d3c6a38c9c1223caab546b9
