### ISSUE TITLE
Keep Store Values Alive Between Components During Router Navigation Subscribing to the Same Selectors

### ISSUE THREAD

**Issue by ugumerie** [state-adapt/state-adapt#52]
Hello,

I want to keep the store and state active when navigating between pages subscribing to the same state and selectors. Example; from a list page to details page.

When navigating from a list page to a details page, the store is destroyed and initialized again which destroys and recreates the state again on loosing subscription between navigations.

How do I maintain the state values between pages so I don't loose the state values when it gets destroyed and initialized on the next page?

Thanks

**Comment by mfp22** [comment]
If you don't ever need it to be destroyed between pages, you can subscribe in the service and it will just hold the state there forever (as long as the service exists).

If you still need it to automatically clean up after the user leaves the 2 routes that need it, you can do this (will get easier in version 2.0):

Create an observable in the service like

```typescript 
delayedUnsubscribe$ = this.store.state$.pipe(
  share({ resetOnRefCountZero: () => timer(1000) }),
);
```

If you unsubscribe to this, the timer will start and then after 1 second it will unsubscribe to the upstream observable. This gives plenty of time for the route to change.

Unfortunately this observable needs to be subscribed to directly in each component. You could do this to some other observable of a selector you're using already and have the async pipe or toSignal subscribe/unsubscribe like normal, but in my opinion it's a little indirect to do it that way. Maybe it's fine.  But maybe someday you stop needing that selector and it's weird that the state is clearing. So you could create an observable specifically for this like the above example and subscribe like this in each component:

```typescript 
sub = this.service.store.delayedUnsubscribe$.pipe(
  takeUntilDestroyed(),
).subscribe();
```

In StateAdapt 2.0 I'm going to add the ability to pass the `share` options into the store itself.

**Comment by ugumerie** [comment]
Thank you for this detailed explanation, I totally get it now. Love your work.

Please, remember to make a detailed documentation/video on StateAdapt 2.0 with all it's wonderful features, and how to migrate incase of breaking changes.

Thanks again and stay awesome.

**Comment by mfp22** [comment]
These are the main changes. https://github.com/state-adapt/state-adapt/issues/45

Also going to remove some deprecated stuff.
