### ISSUE TITLE
From Angular SSR window is not defined

### ISSUE THREAD

**Issue by timsar2** [state-adapt/state-adapt#69]
By adding defaultStoreProvider to the angular ssr config, I got error:

**[vite] Error when evaluating SSR module /main.server.mjs:
|- ReferenceError: window is not defined**

StateAdapt Version: 
"@state-adapt/angular": "^2.0.5",
"@state-adapt/core": "^2.0.5"

```
export const appConfig: ApplicationConfig = {
  providers: [
    defaultStoreProvider,
   ...
}
```

**Comment by mfp22** [comment]
See https://github.com/state-adapt/state-adapt/discussions/68

Hope to have a fix soon. Still wondering about my question in that discussion though

**Comment by timsar2** [comment]
I put my config in #68
