### ISSUE TITLE
Docs for adapt()?

### ISSUE THREAD

**Issue by rpggio** [state-adapt/state-adapt#98]
The tutorials start with `adapt()`, but I don't see it in the API docs. 😕 
In docs, `createAdapter` appears in both `@state-adapt/core` `@state-adapt/core/adapters`.
I appreciate the principles behind this library, but as a beginner it feels idiosyncratic.

**Comment by rpggio** [comment]
I read the Get Started instructions...

**Comment by mfp22** [comment]
I'm adding a big Get Started button in the next release of the docs, right above the tutorial. Thanks for opening the issue. I don't want there to be stupid hurtles like this.

**Comment by mfp22** [comment]
Previously the logos at the top linked to Get Started. It's weird that I didn't realize how crazy this was before now. Now they will link to the tutorial with the framework tab selected, and the Get Started button is the first thing devs will see.

**Comment by rpggio** [comment]
Thanks for staying on top of it. `defaultAdapt` is an export of `@state-adapt/react`, but I don't see in the API docs. It must be the root store?
